version: "3.8"
services:
  selenium:
    image: "selenium/standalone-chrome-debug:3.141.59-20200409"
    ports:
      - "5900:5900"
      - "4444:4444"
  gradle:
    image: "gradle:6.6.1-jdk8"
    depends_on:
      - selenium
    volumes:
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    command: gradle cucumber
